classify/urls.py
from django.urls import path
from .views import (
    ClassifyListView,
    ClassifyDetailView,
    ClassifyCreateView,
    ClassifyUpdateView,
    ClassifyDeleteView
)
from . import views

urlpatterns = [
    path('', views.beranda, name='classify-beranda'),
    path('tutorial/', views.tutorial, name='classify-tutorial'),
    path('riwayat/', ClassifyListView.as_view(), name='classify-riwayat'),
    path('skrining/<int:pk>/hasil/', ClassifyDetailView.as_view(), name='classify-hasil'),
    path('skrining/', ClassifyCreateView.as_view(), name='classify-skrining'),
    path('skrining/<int:pk>/sunting/', ClassifyUpdateView.as_view(), name='classify-sunting'),
    path('skrining/<int:pk>/hapus/', ClassifyDeleteView.as_view(), name='classify-hapus'),
]

health_center/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from users import views as users_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('registrasi/', users_views.registrasi, name='registrasi'),
    path('akun/', users_views.akun, name='akun'),
    path('masuk/', auth_views.LoginView.as_view(template_name='users/masuk.html'), name='masuk'),
    path('keluar/', auth_views.LogoutView.as_view(template_name='users/keluar.html'), name='keluar'),
    path('', include('classify.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classify/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from .utils import contrastStretching, glcm, Node, DecisionTree, RandomForest
from PIL import Image
from io import BytesIO
import numpy as np
import skimage
import pickle
from django.core.files.base import ContentFile

hasil_classify = (
    ('0', 'Normal'),
    ('1', 'Abnormal')
    )

class Classify(models.Model):
    nama_Dokter = models.ForeignKey(User, on_delete=models.CASCADE)
    nama_Pasien = models.CharField(max_length=100)
    tanggal_Lahir = models.DateField()
    nomer_Rekam_Medis = models.CharField(max_length=100)
    gambar_Mammogram = models.ImageField(upload_to='raw_mammogram')
    gambar_Mammogram_Contrast_Stretching = models.ImageField(upload_to='cs_mammogram')
    fitur = models.TextField()
    hasil = models.CharField(choices=hasil_classify, max_length=1)
    tanggal_Skrining = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('classify-hasil', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        new_image_name = self.gambar_Mammogram.name.split("/")[-1]
        image = skimage.img_as_ubyte(skimage.io.imread(self.gambar_Mammogram, as_gray=True))
        image_cs = contrastStretching(image)
        image_glcm = glcm(image_cs)

        model = pickle.load(open('model.pkl', 'rb'))
        image_rf = model.predict([image_glcm])

        cs = skimage.io.imsave('media/cs_mammogram/'+new_image_name, image_cs)
        self.gambar_Mammogram_Contrast_Stretching = 'cs_mammogram/'+new_image_name
        self.fitur = image_glcm
        self.hasil = image_rf
        return super().save(*args, **kwargs)

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegistrasiForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']

classify/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Classify
from django.views.generic import (
    ListView,
    DetailView,
    UpdateView,
    CreateView,
    DeleteView
)

def beranda (request):
    return render(request, 'classify/beranda.html')

def tutorial (request):
    return render(request, 'classify/tutorial.html')

class ClassifyListView(LoginRequiredMixin, ListView):
    model = Classify

    def get_queryset(self):
        return Classify.objects.filter(nama_Dokter = self.request.user).all().order_by('-tanggal_Skrining')

class ClassifyDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Classify

    def test_func(self):
        classify = self.get_object()
        if self.request.user == classify.nama_Dokter:
            return True
        return False

class ClassifyCreateView(LoginRequiredMixin, CreateView):
    model = Classify
    fields = ['nama_Pasien', 'tanggal_Lahir', 'nomer_Rekam_Medis', 'gambar_Mammogram']

    def form_valid(self, form):
        form.instance.nama_Dokter = self.request.user
        return super().form_valid(form)

class ClassifyUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Classify
    fields = ['nama_Pasien', 'tanggal_Lahir', 'nomer_Rekam_Medis', 'gambar_Mammogram', 'hasil']

    def form_valid(self, form):
        form.instance.nama_Dokter = self.request.user
        messages.success(self.request, f'Data skrining berhasil diperbarui!')
        return super().form_valid(form)

    def test_func(self):
        classify = self.get_object()
        if self.request.user == classify.nama_Dokter:
            return True
        return False

class ClassifyDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Classify
    success_url = reverse_lazy('classify-riwayat')

    def form_valid(self, form):
        messages.success(self.request, f'Data skrining berhasil dihapus!')
        return super().form_valid(form)

    def test_func(self):
        classify = self.get_object()
        if self.request.user == classify.nama_Dokter:
            return True
        return False

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegistrasiForm, UserUpdateForm

def registrasi(request):
    if request.method == 'POST':
        form = UserRegistrasiForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Akun berhasil dibuat, silahkan masuk untuk melanjutkan!')
            return redirect('masuk')
    else:
        form = UserRegistrasiForm()
    return render(request, 'users/registrasi.html', {'form':form})

@login_required
def akun (request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        if u_form.is_valid():
            u_form.save()
            messages.success(request, f'Akun berhasil diperbarui!')
            return redirect ('akun')
    else:
        u_form = UserUpdateForm(instance=request.user)

    context = {
        'u_form': u_form
    }
    return render(request, 'users/akun.html', context)

classify/templates/classify/base.html
{%  load static  %}
<!DOCTYPE html>
<html lang="en">
<head>

     <title>Klasifikasi Kanker Payudara</title>
     <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=Edge">
     <meta name="description" content="">
     <meta name="keywords" content="">
     <meta name="author" content="Tooplate">
     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'classify/css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'classify/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'classify/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'classify/css/owl.carousel.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'classify/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'classify/css/tooplate-style.css' %}">


</head>
<body id="top" data-spy="scroll" data-target=".navbar-collapse" data-offset="50">

     <!-- MENU -->
     <section class="navbar navbar-default navbar-static-top" role="navigation">
          <div class="container">

               <div class="navbar-header">
                    <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                         <span class="icon icon-bar"></span>
                         <span class="icon icon-bar"></span>
                         <span class="icon icon-bar"></span>
                    </button>

                    <!-- lOGO TEXT HERE -->
                    <a href="{% url 'classify-beranda' %}" class="navbar-brand"><i class="fa fa-h-square"></i>ealth Center</a>
               </div>

               <!-- MENU LINKS -->
               <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                         <li><a href="{% url 'classify-beranda' %}">Beranda</a></li>
                         <li><a href="{% url 'classify-tutorial' %}">Tutorial</a></li>
                         <li><a href="{% url 'classify-skrining' %}">Skrining</a></li>
                         <li><a href="{% url 'classify-riwayat' %}">Riwayat</a></li>
                         {% if user.is_authenticated %}
                             <li><a href="{% url 'akun' %}" class="smoothScroll">Akun</a></li>
                             <li><a href="{% url 'keluar' %}" class="smoothScroll">Keluar</a></li>
                         {% else %}
                             <li><a href="{% url 'registrasi' %}" class="smoothScroll">Registrasi</a></li>
                             <li><a href="{% url 'masuk' %}" class="smoothScroll">Masuk</a></li>
                         {% endif %}
                    </ul>
               </div>

          </div>
     </section>

     {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" style="margin-bottom: 0px; text-align: center">
                {{ message }}
            </div>
        {% endfor %}
     {% endif %}
     {% block content %}{% endblock content %}

     <!-- FOOTER -->
     <footer data-stellar-background-ratio="5" style ="padding-top:15px; padding-bottom: 10px;">
          <div class="container">
               <div class="col-md-12 col-sm-12, text-align-center">
                    <div class="copyright-text">
                         <p>Copyright &copy; 2022 Sistem Informasi | Fasilkom | UNEJ</p>
                    </div>
               </div>
          </div>
     </footer>

     <!-- SCRIPTS -->
     <script src="{% static 'classify/js/bootstrap.min.js' %}"></script>
     <script src="{% static 'classify/js/custom.js' %}"></script>
     <script src="{% static 'classify/js/jquery.js' %}"></script>
     <script src="{% static 'classify/js/jquery.stellar.min.js' %}"></script>
     <script src="{% static 'classify/js/jquery.sticky.js' %}"></script>
     <script src="{% static 'classify/js/owl.carousel.min.js' %}"></script>
     <script src="{% static 'classify/js/smoothscroll.js' %}"></script>
     <script src="{% static 'classify/js/wow.min.js' %}"></script>

</body>
</html>

classify/templates/classify/beranda.html
{%  extends "classify/base.html"  %}
{% load static %}
{%  block content  %}

<section id="home" class="slider">
     <div class="container">
          <div class="row">
               <div class="item item-first">
                    <div class="caption">
                         <div class="col-md-offset-1 col-md-10">
                              <h3>Skrining</h3>
                              <h1>Kanker Payudara</h1>
                              <a href="{% url 'classify-skrining' %}" class="btn section-btn btn-default">MULAI DETEKSI</a>
                              <div style="padding-top: 10px">
                                   <a href="{% url 'classify-tutorial' %}" class="btn section-btn btn-default">BACA TUTORIAL</a>
                                   <a href="{% url 'classify-riwayat' %}" class="btn section-btn btn-default">LIHAT RIWAYAT</a>
                              </div>
                         </div>
                    </div>
               </div>
          </div>
     </div>
</section>

{%  endblock content  %}

classify/templates/classify/classify_confirm_delete.html
{% extends "classify/base.html" %}
{% load static %}
{% block content %}

<section id="appointment" data-stellar-background-ratio="3" style="padding-top: 20px">
    <div class="section-title" style="text-align: center; padding-bottom: 50px">
        <h3>Skrining Kanker Payudara</h3>
        <a><i class="fa fa-h-square"></i>ealth Center</a>
    </div>

    <div class="container" style="display: flex; align-items: center; justify-content: center;">
        <div class="row col-md-4 col-sm-4" style="padding-right: 5%; padding-left: 5%">
            <form id="appointment-form" role="form" method="POST">
                {% csrf_token %}
                <fieldset class="form-group" style="padding-bottom: 10px">
                    <h5>Apakah yakin ingin menghapus data "{{ object.nama_Pasien }}"?</h5>
                </fieldset>
                <div class="form-group">
                    <button type="submit" class="btn btn-danger" style="width: 49%">HAPUS</button>
                    <a class="btn btn-default" style="width: 49%" href="{% url 'classify-riwayat'%}">BATAL</a>
                </div>
            </form>
        </div>
    </div>
</section>

{%  endblock content  %}

classify/templates/classify/classify_detail.html
{% extends "classify/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<section id="appointment" data-stellar-background-ratio="3" style="padding-top: 20px">
     <div class="section-title" style="padding: 0;">
          <div style="text-align: center;">
               <h3>Hasil Skrining Kanker Payudara</h3>
          </div>
"
          <div class="container" style="display: flex; align-items: center; justify-content: center;" enctype="multipart/form-data">
               <div class="row col-md-4 col-sm-4">
                    <div class="news-info">
                         <img src="{{ classify.gambar_Mammogram.url }}" class="img-responsive">
                         <a href="{{ classify.gambar_Mammogram.url }}">
                              <label>Gambar Asli</label>
                              <i class="fa fa-search-plus"></i>
                         </a>
                    </div>
               </div>

               <div class="row col-md-4 col-sm-4">
                    <div class="news-info">
                         <img src="{{ classify.gambar_Mammogram_Contrast_Stretching.url }}" class="img-responsive">
                         <a href="{{ classify.gambar_Mammogram_Contrast_Stretching.url }}">
                              <label>Gambar Contrast Stretching</label>
                              <i class="fa fa-search-plus"></i>
                         </a>
                    </div>
               </div>

               <div class="row col-md-4 col-sm-4">
                    <div class="team-info">
                         <h3>{{ object.nama_Pasien }}</h3>
                         <small>{{ object.tanggal_Skrining }}</small>
                         <div>
                              <label data-toggle="tooltip" title="Nomor Rekam Medis">
                                   <i class="fa fa-vcard-o"></i> {{ object.nomer_Rekam_Medis }} /</label>
                              <label data-toggle="tooltip" title="Tanggal Lahir">
                                   <i class="fa fa-calendar-o"></i> {{ object.tanggal_Lahir }}</label>
                         </div>
                         <div class="team-contact-info" style="color: #A7B0B2; font-size: 75%">
                              <small>{{ object.fitur }}</small>
                         </div>
                         <div class="team-contact-info">
                              {% if object.hasil == '1' %}
                                   <label>
                                        Hasil :
                                        <label style="color:red; font-weight:bold; font-size: 150%">{{ object.get_hasil_display }}</label>
                                   </label>
                              {% else %}
                                   <label>
                                        Hasil :
                                        <label style="color:blue; font-weight:bold; font-size: 150%">{{ object.get_hasil_display }}</label>
                                   </label>
                              {% endif %}
                         </div>
                         <div style="padding-top: 20px">
                              <a href="{% url 'classify-sunting' object.id %}">
                                   <button class="form-control" id="cf-submit">PERBARUI DATA</button>
                              </a>
                         </div>
                    </div>
               </div>
          </div>
     </div>
</section>

{%  endblock content  %}

classify/templates/classify/classify_form.html
{% extends "classify/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<section id="appointment" data-stellar-background-ratio="3" style="padding-top: 20px">
    <div class="section-title" style="text-align: center;">
        <h3>Skrining Kanker Payudara</h3>
    </div>

    <div class="container" style="display: flex; align-items: center; justify-content: center;">
        <div class="row col-md-4 col-sm-4">
            <form id="appointment-form" role="form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="form-control" id="cf-submit" name="submit">SKRINING</button>
            </form>
        </div>
    </div>
</section>

{%  endblock content  %}

classify/templates/classify/classify_list.html
{%  extends "classify/base.html"  %}
{% load static %}
{%  block content  %}

<section id="appointment" data-stellar-background-ratio="3" style="padding-top: 20px">
    <div class="container">
        <div class="section-title" style="text-align: center;">
            <h3>Riwayat Skrining Kanker Payudara</h3>
        </div>

        <div class="col-md-12 col-sm-12">
            <table class="table table-bordered table-hover">
                <thead style="background-color: #4267b2; color: whitesmoke;">
                    <tr>
                        <th scope="col">Nama Pasien</th>
                        <th scope="col">Tanggal Lahir</th>
                        <th scope="col">No. Rekam Medis</th>
                        <th scope="col">Hasil Skrining</th>
                        <th scope="col">Tanggal Skrining</th>
                        <th scope="col">Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    {% for object in object_list %}
                    <tr>
                        <td>{{ object.nama_Pasien }}</td>
                        <td>{{ object.tanggal_Lahir }}</td>
                        <td>{{ object.nomer_Rekam_Medis }}</td>
                        <td>{{ object.get_hasil_display }}</td>
                        <td>{{ object.tanggal_Skrining }}</td>
                        <td>
                            <a class="btn" style="background-color: #a5c422; color: white" href="{%  url 'classify-hasil' object.id  %}">LIHAT</a>
                            <a class="btn btn-danger" href="{%  url 'classify-hapus' object.id  %}">HAPUS</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>

{%  endblock content  %}

classify/templates/classify/tutorial.html
{%  extends "classify/base.html"  %}
{% load static %}
{%  block content  %}

<section id="about" style="padding-top: 70px;">
     <div class="container">
          <div class="row">
               <div class="col-md-8 col-sm-8">
                    <div class="about-info">
                         <h2>Tutorial Skrining</h2>
                         <div>
                              <img src="{%  static 'classify/images/example-mammogram.png'  %}" width="15%" style="margin-left: 10px; margin-bottom: 10px;">
                              <p>1. Gambar mammogram direkomendasikan berformat .png</p>
                              <p>2. Fokuskan gambar pada bagian payudara saja dengan arah vertikal</p>
                              <p>3. Masukkan identitas pasien dan gambar mammogram pada menu Skrining</p>
                              <p>4. Klik tombol SKRINING untuk melihat hasil apakah payudara normal atau abnormal</p>
                              <p>6. Hasil skrining dapat dilihat kembali pada menu Riwayat</p>
                         </div>
                    </div>
               </div>
          </div>
     </div>
</section>

{%  endblock content  %}

users/templates/users/akun.html
{% extends "classify/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<section id="appointment" data-stellar-background-ratio="3" style="padding-top: 20px">
    <div class="section-title" style="text-align: center;">
        <h3>Akun</h3>
        <label><i class="fa fa-h-square"></i>ealth Center</label>
    </div>

    <div class="container" style="display: flex; align-items: center; justify-content: center;">
        <div class="row col-md-4 col-sm-4">
            <form id="appointment-form" role="form" method="POST" enctype="multipart/form_data">
                {% csrf_token %}
                {{ u_form|crispy }}
                <button type="submit" class="form-control" id="cf-submit" name="submit">PERBARUI AKUN</button>
            </form>
        </div>
    </div>
</section>

{%  endblock content  %}

users/templates/users/keluar.html
{% extends "classify/base.html" %}
{% load static %}
{% block content %}

<section id="appointment" data-stellar-background-ratio="3" style="padding-top: 20px">
    <div class="section-title" style="text-align: center;">
        <h3>Anda telah keluar</h3>
        <label><i class="fa fa-h-square"></i>ealth Center</label>
    </div>
    <div style="text-align: center">
        <p>Masuk kembali? <a href="{% url 'masuk' %}">Masuk</a></p>
    </div>
</section>

{% endblock content %}

users/templates/users/masuk.html
{%  extends "classify/base.html"  %}
{% load static %}
{% load crispy_forms_tags %}
{%  block content  %}

<section id="appointment" data-stellar-background-ratio="3" style="padding-top: 20px">
    <div class="section-title" style="text-align: center;">
        <h3>Masuk</h3>
        <label><i class="fa fa-h-square"></i>ealth Center</label>
    </div>

    <div class="container" style="display: flex; align-items: center; justify-content: center;">
        <div class="row col-md-4 col-sm-4">
            <form id="appointment-form" role="form" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="form-control" id="cf-submit" name="submit">MASUK</button>
            </form>
            <p>Belum punya akun? <a href="{% url 'registrasi' %}">Registrasi</a></p>
        </div>
    </div>
</section>

{%  endblock content  %}

users/templates/users/registrasi.html
{% extends "classify/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<section id="appointment" data-stellar-background-ratio="3" style="padding-top: 20px">
    <div class="section-title" style="text-align: center;">
        <h3>Registrasi</h3>
        <label><i class="fa fa-h-square"></i>ealth Center</label>
    </div>

    <div class="container" style="display: flex; align-items: center; justify-content: center;">
        <div class="row col-md-4 col-sm-4">
            <form id="appointment-form" role="form" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="form-control" id="cf-submit" name="submit">REGISTRASI</button>
            </form>
            <p>Sudah punya akun? <a href="{% url 'masuk' %}">Masuk</a></p>
        </div>
    </div>
</section>

{% endblock content %}